# Generated by Django 6.1 on 2026-09-01 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FinancialDataAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=60)),
                ('record_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='uniq_period_year_month')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('unit_type', models.CharField(choices=[('FACULTY', 'Faculty'), ('DIRECTORATE', 'Directorate'), ('COST_CENTER', 'Cost Center'), ('REVENUE_CENTER', 'Revenue Center'), ('PROFIT_CENTER', 'Profit Center'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='finance.campus')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='finance.organizationunit')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('kpi_code', models.CharField(choices=[('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('SHU', 'SHU'), ('OPERATING_RATIO', 'Operating Ratio'), ('SHU_MARGIN', 'SHU Margin'), ('TF', 'Tuition Fee'), ('NTF_PROJECT', 'NTF Project'), ('NTF_RESEARCH', 'NTF Research')], max_length=30)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(default='%', max_length=20)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='finance.campus')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='finance.organizationunit')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'kpi_code'], name='finance_kpi_year_6b0215_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expense_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('expense_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('shu_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('shu_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='finance.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='finance.financialperiod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='finance.organizationunit')),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'campus'], name='finance_fin_period__145b96_idx'), models.Index(fields=['period', 'campus', 'organization_unit'], name='finance_fin_period__22c856_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueTransactionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_rows', to='finance.campus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_rows', to='finance.organizationunit')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_rows', to='finance.financialperiod')),
                ('revenue_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_rows', to='finance.revenuecategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'campus'], name='finance_rev_period__517b5e_idx'), models.Index(fields=['period', 'campus', 'organization_unit'], name='finance_rev_period__264cd2_idx'), models.Index(fields=['revenue_category'], name='finance_rev_revenue_1ecbcc_idx')],
            },
        ),
    ]
