# Generated by Django 6.1 on 2026-09-03 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RkaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('version_code', models.CharField(max_length=30)),
                ('version_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year', '-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PPMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pp_code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pp_codes', to='finance.organizationunit')),
            ],
            options={
                'ordering': ['pp_code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(blank=True, default='', max_length=60)),
                ('contract_code', models.CharField(blank=True, default='', max_length=60)),
                ('project_name', models.CharField(blank=True, default='', max_length=300)),
                ('project_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('source_status', models.CharField(blank=True, default='', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='finance.campus')),
                ('first_seen_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financialperiod')),
                ('last_seen_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financialperiod')),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='finance.organizationunit')),
                ('pp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='finance.ppmaster')),
            ],
            options={
                'ordering': ['project_number'],
            },
        ),
        migrations.CreateModel(
            name='NtfReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('source_total_recognized', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('source_current_year_recognized', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('unit_raw', models.CharField(blank=True, default='', max_length=200)),
                ('organization_raw', models.CharField(blank=True, default='', max_length=200)),
                ('project_name_raw', models.CharField(blank=True, default='', max_length=300)),
                ('contract_code_raw', models.CharField(blank=True, default='', max_length=60)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ntf_snapshots', to='finance.financialperiod')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntf_snapshots', to='finance.project')),
            ],
            options={
                'ordering': ['-loaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_raw', models.CharField(max_length=300)),
                ('alias_normalized', models.CharField(blank=True, default='', max_length=300)),
                ('source', models.CharField(default='GL', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_aliases', to='finance.ppmaster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='finance.project')),
            ],
            options={
                'ordering': ['-is_verified', 'alias_normalized'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_ytd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('recognized_month', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('closing_ytd', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('opening_lifetime', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('closing_lifetime', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('project_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('remaining_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status_at_close', models.CharField(blank=True, default='', max_length=30)),
                ('is_frozen', models.BooleanField(default=True)),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_monthly_snapshots', to='finance.financialperiod')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_snapshots', to='finance.project')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=40)),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('subcategory', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.revenuecategory')),
            ],
            options={
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='RevenueBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('annual_budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.ppmaster')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.revenueaccount')),
                ('rka_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.rkaversion')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='RevenueBudgetMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('revenue_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rows', to='finance.revenuebudget')),
            ],
            options={
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='RevenueLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_transaction_id', models.CharField(blank=True, default='', max_length=64)),
                ('source_line_id', models.CharField(blank=True, default='', max_length=64)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('voucher_number', models.CharField(blank=True, default='', max_length=60)),
                ('document_number', models.CharField(blank=True, default='', max_length=60)),
                ('account_code_raw', models.CharField(blank=True, default='', max_length=40)),
                ('account_name_raw', models.CharField(blank=True, default='', max_length=200)),
                ('description_raw', models.TextField(blank=True, default='')),
                ('pp_code_raw', models.CharField(blank=True, default='', max_length=20)),
                ('description_normalized', models.TextField(blank=True, default='')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenue_ledger_rows', to='finance.financialperiod')),
                ('pp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_rows', to='finance.ppmaster')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_rows', to='finance.revenueaccount')),
            ],
            options={
                'ordering': ['posting_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GLProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('match_method', models.CharField(blank=True, default='', max_length=30)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('match_status', models.CharField(choices=[('AUTO_MATCHED', 'Auto Matched'), ('VERIFIED', 'Verified'), ('NEEDS_REVIEW', 'Needs Review'), ('UNMATCHED', 'Unmatched')], default='UNMATCHED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_mappings', to='finance.project')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_mappings', to='finance.revenueledger')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('is_frozen', models.BooleanField(default=True)),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_monthly_snapshots', to='finance.financialperiod')),
                ('pp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_monthly_snapshots', to='finance.ppmaster')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_monthly_snapshots', to='finance.revenueaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SimkugSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('GL', 'General Ledger'), ('NTF', 'NTF Report'), ('RKA', 'RKA')], max_length=10)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='RUNNING', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_upserted', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.financialperiod')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_number'], name='finance_pro_project_b001b1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['pp'], name='finance_pro_pp_id_064f54_idx'),
        ),
        migrations.AddIndex(
            model_name='ntfreportsnapshot',
            index=models.Index(fields=['project', 'period'], name='finance_ntf_project_06fd44_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmonthlysnapshot',
            index=models.Index(fields=['period'], name='finance_pro_period__fb7142_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmonthlysnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'period'), name='uniq_project_monthly_snapshot'),
        ),
        migrations.AddIndex(
            model_name='revenueaccount',
            index=models.Index(fields=['account_code', 'is_active'], name='finance_rev_account_9dd723_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenueaccount',
            constraint=models.UniqueConstraint(fields=('account_code', 'valid_from'), name='uniq_account_code_valid_from'),
        ),
        migrations.AddConstraint(
            model_name='revenuebudgetmonthly',
            constraint=models.UniqueConstraint(fields=('revenue_budget', 'month'), name='uniq_revenue_budget_month'),
        ),
        migrations.AddIndex(
            model_name='revenueledger',
            index=models.Index(fields=['posting_date'], name='finance_rev_posting_ca88b4_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueledger',
            index=models.Index(fields=['period'], name='finance_rev_period__1de6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueledger',
            index=models.Index(fields=['pp'], name='finance_rev_pp_id_cc68e2_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueledger',
            index=models.Index(fields=['revenue_account'], name='finance_rev_revenue_924023_idx'),
        ),
        migrations.AddIndex(
            model_name='revenueledger',
            index=models.Index(fields=['source_transaction_id'], name='finance_rev_source__bbc046_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenueledger',
            constraint=models.UniqueConstraint(condition=models.Q(('source_transaction_id__gt', '')), fields=('source_transaction_id', 'source_line_id'), name='uniq_ledger_source_tx_line'),
        ),
        migrations.AddIndex(
            model_name='glprojectmapping',
            index=models.Index(fields=['ledger'], name='finance_glp_ledger__56afcc_idx'),
        ),
        migrations.AddIndex(
            model_name='glprojectmapping',
            index=models.Index(fields=['project'], name='finance_glp_project_a5d26f_idx'),
        ),
        migrations.AddIndex(
            model_name='glprojectmapping',
            index=models.Index(fields=['match_status'], name='finance_glp_match_s_624dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='revenuemonthlysnapshot',
            index=models.Index(fields=['period', 'pp', 'revenue_account'], name='finance_rev_period__1c27eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenuemonthlysnapshot',
            constraint=models.UniqueConstraint(fields=('period', 'pp', 'revenue_account'), name='uniq_revenue_monthly_snapshot'),
        ),
        migrations.AddIndex(
            model_name='revenuebudget',
            index=models.Index(fields=['year', 'pp', 'revenue_account'], name='finance_rev_year_11bbe0_idx'),
        ),
        migrations.AddConstraint(
            model_name='revenuebudget',
            constraint=models.UniqueConstraint(fields=('rka_version', 'year', 'pp', 'revenue_account'), name='uniq_rka_version_year_pp_account'),
        ),
        migrations.AddIndex(
            model_name='simkugsynclog',
            index=models.Index(fields=['sync_type', 'status'], name='finance_sim_sync_ty_38b3b9_idx'),
        ),
    ]
