# Generated by Django 6.1 on 2026-09-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rkaversion_ppmaster_project_ntfreportsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueaccount',
            name='detail_history_mode',
            field=models.CharField(choices=[('PERIOD_ONLY', 'Period Only'), ('HISTORICAL', 'Historical')], default='HISTORICAL', max_length=20),
        ),
    ]
