# Generated by Django 6.1 on 2026-09-16 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_revenueaccount_detail_history_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdataauditlog',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='source_type',
            field=models.CharField(choices=[('IMPORTED', 'Imported'), ('MANUAL', 'Manual')], default='IMPORTED', max_length=20),
        ),
        migrations.CreateModel(
            name='ManualRevenueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('ADJUSTMENT', 'Adjustment')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('VOID', 'Void')], default='POSTED', max_length=10)),
                ('transaction_date', models.DateField()),
                ('evidence_number', models.CharField(blank=True, default='', max_length=60)),
                ('document_number', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='finance.organizationunit')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='finance.financialperiod')),
                ('pp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='finance.ppmaster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='finance.project')),
                ('reference_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_adjustments', to='finance.revenueledger')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='finance.revenueaccount')),
                ('revenue_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries', to='finance.revenuecategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
                'permissions': [('restore_entry', 'Can restore a voided manual revenue entry'), ('create_adjustment', 'Can create an adjustment entry'), ('view_audit', 'Can view the manual revenue audit history')],
                'indexes': [models.Index(fields=['status', 'period'], name='finance_man_status_384012_idx'), models.Index(fields=['project', 'revenue_account', 'status'], name='finance_man_project_aa284f_idx'), models.Index(fields=['pp', 'revenue_account', 'status'], name='finance_man_pp_id_6663fd_idx'), models.Index(fields=['transaction_date'], name='finance_man_transac_c24f84_idx')],
            },
        ),
    ]
