# Generated by Django 6.1 on 2026-09-18 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financialdataauditlog_reason_project_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIntakeImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('new_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PREVIEWED', max_length=12)),
                ('message', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_intake_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentIntakeTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_program_code', models.CharField(max_length=80)),
                ('faculty_name', models.CharField(max_length=200)),
                ('study_program_name', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('tariff', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('quota', models.PositiveIntegerField(default=0)),
                ('registration', models.PositiveIntegerField(default=0)),
                ('source_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_intake_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'faculty_name', 'study_program_name'],
                'indexes': [models.Index(fields=['faculty_name', 'year'], name='finance_stu_faculty_6d9157_idx'), models.Index(fields=['study_program_code', 'year'], name='finance_stu_study_p_ee98ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('study_program_code', 'year'), name='student_intake_code_year_unique'), models.CheckConstraint(condition=models.Q(('year__gte', 1900), ('year__lte', 2200)), name='student_intake_year_range'), models.CheckConstraint(condition=models.Q(('tariff__isnull', True), ('tariff__gte', 0), _connector='OR'), name='student_intake_tariff_nonnegative'), models.CheckConstraint(condition=models.Q(('quota__gte', 0)), name='student_intake_quota_nonnegative'), models.CheckConstraint(condition=models.Q(('registration__gte', 0)), name='student_intake_registration_nonnegative')],
            },
        ),
    ]
